Nama = input("Masukkan nama anda : ")
Nim = input("Masukkan Nim anda : ")
Tempat_tinggal_tanggal_lahir = input("Masukkan Tempat tanggal lahir anda : ")
umur = input("Masukkan umur anda : ")
jenis_kelamin = input(" Masukkan jenis kelamin anda : ")
jurusan = input("Masukkan jurusan anda : ")
alamat = input("Masukkan alamat anda : ")

print("Kamu adalah : "+Nama)
print("Nim kamu adalah : "+Tempat_tinggal_tanggal_lahir)
print("umur kamu adalah : "+umur)
print("jenis kelamin kamu adalah : "+jenis_kelamin)
print("jurusan kamu adalah : "+jurusan)
print("alamat kamu adalah : "+alamat)